name: Gtest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: gtest-permission
      run: chmod a+x ./Campus_Recruitment/all.out 
    - name: gtest
      run: ./Campus_Recruitment/all.out 
